# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'bet305' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bet305

    pod 'AFNetworking', '~> 3.2.1'
    pod 'Masonry', '~> 1.1.0'
    pod 'SDWebImage', '~> 3.7.2'
    pod 'MJRefresh', '~> 3.1.15.3'
    pod 'MWPhotoBrowser', '2.1.2'
    pod 'Toast', '4.0.0'
    pod 'YYText', '~> 1.0.7'
    pod 'LCBannerView', '~> 2.1.1'
    #pod 'SwipeTableView'

    # shareSDk
    pod 'mob_sharesdk'
    pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
    pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
    pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'  
    # pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull' //（微信sdk带支付的命令，和上面不带支付的不能共存，只能选择一个）
    pod 'mob_sharesdk/ShareSDKPlatforms/Facebook'
    pod 'mob_sharesdk/ShareSDKPlatforms/Twitter'

end
